version: "3.8"

services:
  docsify:
    container_name: docsify-server
    image: ghcr.io/rockbenben/docsify-server:latest
    volumes:
      - ./docs:/docs
    ports:
      - "8080:3000"
    restart: unless-stopped
